In [6]:
import sklearn as sl
import sklearn.metrics as metrics
import numpy as np

In [13]:
y_true = np.array([[0, 0], [0, 1]])
y_pred =np.ones((2, 2))

In [14]:
y_true

array([[0, 0],
       [0, 1]])

In [15]:
y_pred

array([[1., 1.],
       [1., 1.]])

In [16]:
metrics.accuracy_score(y_true,y_pred, normalize=False)

0

In [62]:
y_true = np.random.randint(0,3,size=(20))
y_pred = np.random.randint(0,3,size=(20))

In [63]:
y_true

array([0, 2, 1, 0, 1, 2, 0, 1, 1, 1, 2, 0, 1, 1, 0, 2, 0, 1, 2, 1])

In [64]:
y_pred

array([0, 2, 0, 1, 2, 1, 1, 1, 1, 2, 2, 1, 0, 1, 1, 0, 1, 2, 1, 0])

In [65]:
metrics.precision_score(y_true,y_pred,average=None)

array([0.2, 0.3, 0.4])

In [66]:
metrics.precision_score(y_true,y_pred,average='micro')

0.3

In [67]:
metrics.precision_score(y_true,y_pred,average='macro')

0.3

In [69]:
metrics.precision_score(y_true,y_pred,average='weighted')

0.29500000000000004

In [68]:
metrics.confusion_matrix(y_true,y_pred)

array([[1, 5, 0],
       [3, 3, 3],
       [1, 2, 2]])